---
ansible_connection: network_cli
ansible_network_os: routeros
ansible_user: administrator
ansible_ssh_private_key_file: /home/user/.ssh/id_rsa
version: '                  version: 6.46.1 (stable)'
